# IPython log file

runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
------------------------------------------
print "--------------------------------"
print ("--------------------------------")
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
print ("--------------------------------")
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
print ("--------------------------------")
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
print ("--------------------------------")
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
dir
#[Out]# <built-in function dir>
get_ipython().run_line_magic('logstart%', '-o')
get_ipython().run_line_magic('logstop%', '')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
get_ipython().run_line_magic('reset', '')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
debugfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
runfile('C:/Users/pensi/source/repos/ENM360/Week2/power-iterations-for-eigens-PROBLEM1.py', wdir='C:/Users/pensi/source/repos/ENM360/Week2')
scientific
$scientific
